messages:
  no_found_player: 'Не найден {player} [Код ошибки: 1]'
  no_found_item: 'Не найден предмет [Код ошибки: 2]'
items:
  ender:
    name: ' &#ff5c00Эндермен'
    lore:
      - ''
      - ' &7Особенность и применение:'
      - ' &#ff5c00- когда предмет в инвентаре, с шансом в 50%'
      - ' &#ff5c00  не потратится эндер-жемчуг, при его броске'
      - ''
    glow: true # Включить свечение предмета?
    chache: 0.50 # Шанс чтобы не потерять эндер чемчуг
  illum:
    material: SEA_LANTERN
    name: ' &#e3fbe1И&#e3fbe1л&#e3fbe1л&#e3fbe1ю&#e3fbe1м&#e3fbe1и&#e3fbe1н&#e3fbe1а&#e3fbe1т&#e3fbe1о&#e3fbe1р'
    lore:
      - ''
      - ' &7Особенность и применение:'
      - ' &#e3fbe1- при ударе, есть шанс 25% дать игроку,'
      - ' &#e3fbe1  по которому совершен удар,'
      - ' &#e3fbe1  эффект свечение на 15 секунд'
      - ''
    glow: true # Включить свечение предмета?
    chache: 0.25 # Шанс на выдачу эффекта(-ов)
    give-effects-opponent: # Можно создавать бесконечно
      # Имя эффекта;время эффекта в секундах;сила эффекта
      - 'GLOWING;15;1'
  grav:
    material: FEATHER
    name: '&6Гравитация &8&o(предмет)'
    lore:
      - ''
      - '§7Особенности и применение:'
      - '§6- когда предмет в ивентаре, ваш персонаж'
      - '§6  не получает урон от падения.'
      - ''
    actionbar:
      enable: true
      text: 'Только что сработал эффект: «Гравитация»'
  artefender:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &#ff5c00- Эндермен'
      - ''
    chachetp: 0.50 # Шанс чтобы не потерять эндер чемчуг
  artef:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
  artefall:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &#ff5c00- Эндермен'
      - ' &6- Гравитация'
      - ' &#e3fbe1- И&#e3fbe1л&#e3fbe1л&#e3fbe1ю&#e3fbe1м&#e3fbe1и&#e3fbe1н&#e3fbe1а&#e3fbe1т&#e3fbe1о&#e3fbe1р'
      - ''
    chachetp: 0.50
    chacheillum: 0.25
    give-effects-opponent:
      - 'GLOWING;15;1'
    actionbar:
      enablegrav: true
      textgrav: 'Только что сработал эффект: «Гравитация»'
  artefillum:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &#e3fbe1- И&#e3fbe1л&#e3fbe1л&#e3fbe1ю&#e3fbe1м&#e3fbe1и&#e3fbe1н&#e3fbe1а&#e3fbe1т&#e3fbe1о&#e3fbe1р'
      - ''
    chacheillum: 0.25
    give-effects-opponent:
      - 'GLOWING;15;1'
  artefgrav:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &6- Гравитация'
      - ''
    actionbar:
      enablegrav: true
      textgrav: 'Только что сработал эффект: «Гравитация»'
  artefillumandgrav:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &6- Гравитация'
      - ' &#e3fbe1- И&#e3fbe1л&#e3fbe1л&#e3fbe1ю&#e3fbe1м&#e3fbe1и&#e3fbe1н&#e3fbe1а&#e3fbe1т&#e3fbe1о&#e3fbe1р'
      - ''
    chacheillum: 0.25
    give-effects-opponent:
      - 'GLOWING;15;1'
    actionbar:
      enablegrav: true
      textgrav: 'Только что сработал эффект: «Гравитация»'
  artefgravandender:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &6- Гравитация'
      - ' &#ff5c00- Эндермен'
      - ''
    chachetp: 0.50
    actionbar:
      enablegrav: true
      textgrav: 'Только что сработал эффект: «Гравитация»'
  artefillumandender:
    name: ' &#ff5c00Артефакт'
    lore:
      - ' &fМожет активировать сразу несколько'
      - ' &fразных предметов Хранителя Опыта.'
      - ' &f'
      - ' &7Совмещённые эффекты:'
      - ' &#ff5c00- Эндермен'
      - ' &#e3fbe1- И&#e3fbe1л&#e3fbe1л&#e3fbe1ю&#e3fbe1м&#e3fbe1и&#e3fbe1н&#e3fbe1а&#e3fbe1т&#e3fbe1о&#e3fbe1р'
      - ''
    chachetp: 0.50
    chacheillum: 0.25
    give-effects-opponent:
      - 'GLOWING;15;1'